#!/usr/bin/env bash

###################################################################
#Script Name	: launchPicom
#Description	: kill all picom istances and run it
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

# Terminate already running picom istances
killall -q picom

# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

picom --config /home/fedeizzo/.config/picom/picom.conf -b &
# monitorHdmi=$(xrandr -q | grep HDMI1 | awk '{print $2}')
# isHdmiPrimary=$(xrandr -q | grep HDMI1 | awk '{print $3}')
# monitorDp1=$(xrandr -q | grep '^DP1' | awk '{print $2}')
# if [[ $monitorHdmi == 'connected' && $isHdmiPrimary != 'primary' ]]
# then
#     picom --config /home/fedeizzo/.config/picom/picom.conf -b &
# elif [[ $monitorDp1 == 'connected' ]]
# then
#     picom --config /home/fedeizzo/.config/picom/picom.conf -b &
# fi
